# Generated by Django 4.0.1 on 2022-01-12 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPUChipset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipset', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GPUList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_link', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GPUManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField()),
                ('price', models.FloatField(default=-1)),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpu_scraper.gpulist')),
            ],
        ),
        migrations.CreateModel(
            name='GPUType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('memory_size', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpu_scraper.gpumanufacturer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpu_scraper.gpuchipset')),
            ],
        ),
        migrations.AddField(
            model_name='gpulist',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpu_scraper.marketplace'),
        ),
        migrations.AddField(
            model_name='gpulist',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpu_scraper.gputype'),
        ),
    ]
