# Generated by Django 4.0.1 on 2022-01-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gputype',
            options={'ordering': ['product_name']},
        ),
    ]
