# Generated by Django 4.0.1 on 2022-01-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_scraper', '0002_alter_gputype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpuchipset',
            options={'ordering': ['chipset']},
        ),
        migrations.AlterModelOptions(
            name='gpulist',
            options={'ordering': ['model', 'marketplace']},
        ),
        migrations.AlterModelOptions(
            name='gpumanufacturer',
            options={'ordering': ['manufacturer']},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['-price_date', 'gpu']},
        ),
    ]
