# Generated by Django 4.0.1 on 2022-03-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_scraper', '0003_alter_gpuchipset_options_alter_gpulist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gputype',
            name='product_name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='gpulist',
            unique_together={('model', 'marketplace')},
        ),
    ]
