# Generated by Django 4.0.1 on 2022-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_scraper', '0004_alter_gputype_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpulist',
            name='asin',
            field=models.CharField(default='', max_length=50),
        ),
    ]
